"""empty message

Revision ID: e7432557a6d4
Revises: fc29c466d15c
Create Date: 2023-07-01 06:03:42.855942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7432557a6d4'
down_revision = 'fc29c466d15c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=150), nullable=False))
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.drop_column('description')

    # ### end Alembic commands ###
